---
repos:
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v25.1.3
    hooks:
      - id: ansible-lint
        always_run: false
        pass_filenames: true
        files: \.(yaml|yml)$
        exclude: /env[^/]*.(yaml|yml)$
        entry: |-
          ansible-lint
            --offline
            --profile production
            --exclude tests/integration/
            --exclude tests/unit/
            --parseable
            --nocolor
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
  - repo: https://github.com/pycqa/pylint
    rev: v3.3.5
    hooks:
      - id: pylint
        args:
          - --disable=import-error
        files: \.py$
...
