---
namespace: farrapos
name: homelab
version: 0.3.0
readme: README.md
authors:
  - Rafael Guterres Jeffman <rafasgj@gmail.com>
description: "A collection to set services using low-end Raspberry Pi"
license:
  - GPL-3.0-or-later
tags: [homelab, raspberry, services]

dependencies:
  ansible.posix: '*'

repository: https://github.com/rafasgj/farrapos_homelab
documentation: https://github.com/rafasgj/farrapos_homelab
homepage: https://github.com/rafasgj/farrapos_homelab
issues: https://github.com/rafasgj/farrapos_homelab/issues

build_ignore: []
