FROM alpine:latest

RUN apk update
RUN apk add --no-cache unbound bind-tools iputils

RUN mkdir -p /etc/unbound
RUN chown root:unbound /etc/unbound
RUN chmod 775 /etc/unbound

VOLUME [ "/etc/unbound" ]

ENTRYPOINT ["unbound", "-d"]
