---
- name: Disable systemd-resolved
  ansible.builtin.systemd_service:
    name: systemd-resolved
    enabled: false
    state: stopped

- name: Start services
  ansible.builtin.systemd_service:
    name: "farrapos-dns-{{ item }}"
    daemon_reload: true
    enabled: true
    state: restarted
  loop:
    - pod
    - network
    - nameserver
    - filter
